name: Deploy to Firebase

on:
  push:
    branches:
      - main

env:
  FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Fetch Firebase secret from GitHub Secrets
        
      #   run: |
      #     echo "FIREBASE_KEY=${FIREBASE_KEY}" >> .env
          
      # - name: Print .env content
      #   run: cat .env


      - name: Run application
        run: ./run.sh
